# Generated by Django 5.2.14 on 2026-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/%Y/%m/%d/')),
                ('model_type', models.CharField(choices=[('resnet', 'ResNet18'), ('xgboost', 'XGBoost')], max_length=20)),
                ('predicted_class', models.CharField(choices=[('NonDemented', 'NonDemented'), ('VeryMildDemented', 'VeryMildDemented'), ('MildDemented', 'MildDemented'), ('ModerateDemented', 'ModerateDemented')], max_length=50)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField()),
                ('apply_preprocess', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tahmin Kaydı',
                'verbose_name_plural': 'Tahmin Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
