# Generated by Django 5.2.14 on 2026-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='model_type',
            field=models.CharField(choices=[('resnet', 'ResNet18'), ('xgboost', 'XGBoost'), ('yolo', 'YOLOv8')], max_length=20),
        ),
    ]
